// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXItWD1MnDp64d1o2pD9spMw9vj4JU9t8',
    appId: '1:104539423398:web:0fe8235bba15f7a2f8ea67',
    messagingSenderId: '104539423398',
    projectId: 'scraps2dishes',
    authDomain: 'scraps2dishes.firebaseapp.com',
    storageBucket: 'scraps2dishes.appspot.com',
    measurementId: 'G-EY5P7MRXNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTJ5ceKhgUlRsd2Mq9nOQ1yECekNLvXWI',
    appId: '1:104539423398:android:a056e6b98a7603e7f8ea67',
    messagingSenderId: '104539423398',
    projectId: 'scraps2dishes',
    storageBucket: 'scraps2dishes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFEv3IhH0bcETVb_iPCAZEyWXk4zEapqA',
    appId: '1:104539423398:ios:a1d4541b16d08f50f8ea67',
    messagingSenderId: '104539423398',
    projectId: 'scraps2dishes',
    storageBucket: 'scraps2dishes.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFEv3IhH0bcETVb_iPCAZEyWXk4zEapqA',
    appId: '1:104539423398:ios:cd7eacc070393c05f8ea67',
    messagingSenderId: '104539423398',
    projectId: 'scraps2dishes',
    storageBucket: 'scraps2dishes.appspot.com',
    iosBundleId: 'com.example.app1.RunnerTests',
  );
}
